@BASE_URL = http://localhost:3333/api

@token = "65d3bc42ea3d7-8052265b337c9144768ddc1bded35f2f-amTP6Vio44e8GQfDD"


# @name all-products
GET {{BASE_URL}}/fetch-and-save
Accept: application/json
Content-Type: application/json

###

# @name product-stock
GET https://connectplug.com.br/api/v2/product-stock-balance/1
Accept: application/json
Content-Type: application/json
Authorization: 65d3bc42ea3d7-8052265b337c9144768ddc1bded35f2f-amTP6Vio44e8GQfDD

###

# @name all-products-atributes
GET https://connectplug.com.br/api/v2/product-attribute
Accept: application/json
Content-Type: application/json
Authorization: 65d3bc42ea3d7-8052265b337c9144768ddc1bded35f2f-amTP6Vio44e8GQfDD

###

# @name all-products-supliers
GET https://connectplug.com.br/api/v2/product/1/supplier
Accept: application/json
Content-Type: application/json
Authorization: 65d3bc42ea3d7-8052265b337c9144768ddc1bded35f2f-amTP6Vio44e8GQfDD

###

# @name all-products-stock
GET https://connectplug.com.br/api/v2/product-stock-balance
Accept: application/json
Content-Type: application/json
Authorization: 65d3bc42ea3d7-8052265b337c9144768ddc1bded35f2f-amTP6Vio44e8GQfDD

###

# @name show-product-attribute
GET https://connectplug.com.br/api/v2/product-attribute/1
Accept: application/json
Content-Type: application/json
Authorization: 65d3bc42ea3d7-8052265b337c9144768ddc1bded35f2f-amTP6Vio44e8GQfDD

###

# @name show-product-suplyer
GET https://connectplug.com.br/api/v2/product/1/supplier
Accept: application/json
Content-Type: application/json
Authorization: 65d3bc42ea3d7-8052265b337c9144768ddc1bded35f2f-amTP6Vio44e8GQfDD

###

# @name show-product-suplyer
GET https://connectplug.com.br/api/v2/sale
Accept: application/json
Content-Type: application/json
Authorization: 65d3bc42ea3d7-8052265b337c9144768ddc1bded35f2f-amTP6Vio44e8GQfDD

