@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

###

# @name create-brand
POST {{BASE_URL}}/brands
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "marca 6"
  
}

###

# @name get-brands
GET  {{BASE_URL}}/brands
Content-Type: application/json

###

# @name delete-brands
Delete  {{BASE_URL}}/brands/270d50a6-1f97-43e1-96b7-8e909a67cf79
Content-Type: application/json

###

# @name find-brand-by-id
GET  {{BASE_URL}}/brands/d5d1b4d6-3449-461a-8efd-a5179b43a6f4
Content-Type: application/json

###

# @name edit-brand
PUT  {{BASE_URL}}/brands/270d50a6-1f97-43e1-96b7-8e909a67cf79
Content-Type: application/json

{
  "name": "brand 2"
  
}




