@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}


# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "brunao@bruno.com",
  "password": "123456aA@"
}


###
# @name get-all-products
GET {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###
# @name create-cart
POST {{BASE_URL}}/cart
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "userId": "5872ff3d-aed1-4038-9864-d43ef44f736e",
    "items": [

          {
            "productId": "1e3ca1c8-b1f1-4b60-9033-e18fffd96c21",
            "quantity": 2,
            "price": 112.00,
            "colorId": "preto",
            "sizeId":"g"
        }
        # {
        #     "productId": "6b60d2ab-5b75-47db-adae-a8cf0cabb423",
        #     "quantity": 12,
        #     "price": 105.00
        # }
      
          ]
}


###

# @name add-item-cart
POST {{BASE_URL}}/cart/add-item/c775386f-cfc3-427a-ad34-fed0f8687147
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "productId": "675936ca-f2b2-4e2b-8b2c-27c15853627e",
    "quantity": 2,
    "price": 200,
    "height": 11,
    "width": 16,
    "length": 26,
    "weight": 2.5
  

}


###
# @name check-cart-exist
GET {{BASE_URL}}/cart/c775386f-cfc3-427a-ad34-fed0f8687147/exists
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}



###
# @name get-the-cart-by-userId
GET {{BASE_URL}}/cart/user/76345bcb-2d1b-450e-af2b-dd1a290c3a1c
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}



###
# @name delete-item-cart
DELETE {{BASE_URL}}/cart/63c0f430-db37-48bc-bcee-d943ee79c2e5/item/02abb5ed-3bb2-4052-91a1-f47284a3c6f4
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}



###

