@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}


# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "brunao@bruno.com",
  "password": "123456aA@"
}


###
# @name get-all-products
GET {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###
# @name create-cart
POST {{BASE_URL}}/cart
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "userId": "799a657b-45c2-4c1e-82d4-7cc0bc9515a0",
    "items": [

        #   {
        #     "productId": "1e3ca1c8-b1f1-4b60-9033-e18fffd96c21",
        #     "quantity": 2,
        #     "price": 112.00,
        #     "colorId": "preto",
        #     "sizeId":"g"
        # }

        {
            "productId": "c2d0b703-af33-4385-811c-87eb815d5ce4",
            "quantity": 2,
            "price": 204.00,
            "hasVariants": false
        }
      
          ]
}


###

# @name add-item-cart
POST {{BASE_URL}}/cart/add-item/799a657b-45c2-4c1e-82d4-7cc0bc9515a0
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "productId": "c2d0b703-af33-4385-811c-87eb815d5ce4",
    "quantity": 1,
    "price": 204,
    "height": 14,
    "width": 16,
    "length": 27,
    "weight": 1.5,
    "hasVariants": false
  

}


###
# @name check-cart-exist
GET {{BASE_URL}}/cart/c775386f-cfc3-427a-ad34-fed0f8687147/exists
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}



###
# @name get-the-cart-by-userId
GET {{BASE_URL}}/cart/user/799a657b-45c2-4c1e-82d4-7cc0bc9515a0
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}



###
# @name delete-item-cart
DELETE {{BASE_URL}}/cart/63c0f430-db37-48bc-bcee-d943ee79c2e5/item/02abb5ed-3bb2-4052-91a1-f47284a3c6f4
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}



###

