@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}


# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "brunao@bruno.com",
  "password": "123456aA@"
}


###
# @name get-all-products
GET {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###
# @name create-cart
POST {{BASE_URL}}/cart
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "userId": "c775386f-cfc3-427a-ad34-fed0f8687147",
    "items": [

          {
            "productId": "2fac9f52-b6a2-4677-a6e4-dfa15ecccd5d",
            "quantity": 2,
            "price": 112.00,
            "colorId": "preto",
            "sizeId":"g"
        }
        # {
        #     "productId": "6b60d2ab-5b75-47db-adae-a8cf0cabb423",
        #     "quantity": 12,
        #     "price": 105.00
        # }
      
          ]
}


###

