@BASE_URL = http://localhost:3333

# @name create-color
POST {{BASE_URL}}/colors
Content-Type: application/json

{
  "name": "vermelho"
  
}

###

# @name get-colors
GET  {{BASE_URL}}/colors
Content-Type: application/json


