@BASE_URL = http://localhost:3333

# @name create-color
POST {{BASE_URL}}/colors
Content-Type: application/json

{
  "name": "rosa"
  
}

###

# @name get-colors
GET  {{BASE_URL}}/colors
Content-Type: application/json

###

# @name delete-colors
Delete  {{BASE_URL}}/colors/480d3a04-de4c-4620-991d-a720c3a11fdb
Content-Type: application/json

###

# @name find-color-by-id
GET  {{BASE_URL}}/colors/d1f4f8e2-d580-4f5c-ae75-e5df1648d409
Content-Type: application/json




