@BASE_URL = http://localhost:3333

@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

###

# @name create-category
POST {{BASE_URL}}/category
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "category 8"
  
}

###

# @name get-category-by-name
GET  {{BASE_URL}}/category?name=category 2
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name delete-category
Delete  {{BASE_URL}}/category/84f4d873-5af4-453d-85d3-a1f26a01ee65
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: application/json

###

# @name find-category-by-id
GET  {{BASE_URL}}/category/84f4d873-5af4-453d-85d3-a1f26a01ee65
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: application/json

###


# @name get-category-all
GET {{BASE_URL}}/category/all?page=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###

# @name edit-brand
PUT  {{BASE_URL}}/category/84f4d873-5af4-453d-85d3-a1f26a01ee65
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: application/json

{
  "name": "category 2"
  
}




