@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}



# @name authenticate-admin
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

###

# @name create-account
POST {{BASE_URL}}/accounts
Content-Type: application/json

{
  "name": "bruno",
  "email": "bru@bruno.com",
  "password":"123456"
}

###



# @name update-account
PUT {{BASE_URL}}/accounts/27997069-e5ed-4af7-a428-e6f32c102c8e
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "email": "brunao@brunao.com"
 
}

###
# @name delete-account
DELETE {{BASE_URL}}/accounts/109eaa76-5b9b-4912-b2c9-e24d5c96eefa
Content-Type: application/json


###

# @name create-account-google
POST {{BASE_URL}}/accounts/google
Content-Type: application/json

{
  "name": "bruno",
  "email": "brunogmdaddifld@bruno.com",
  "googleUserId": "123456",
  "profileImageUrl": "https://www.google.com.br"
}


###

# @name check-if-email-exists
POST {{BASE_URL}}/accounts/check
Content-Type: application/json

{
  "email": "wbrunovieira17@gmail.com"
}


### 



# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

###
# @name get-all-accounts
GET {{BASE_URL}}/accounts?page=1
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###

# @name create-products
POST {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "blusa 1515",
  "description": "calcinha description 1 mais texto, legal, muiito legal" ,
  "images": ["/images/foto1.jpg"],
  "materialId": "508882db-4aef-4e62-a07d-5b6770efb36b",
  "brandId": "598979ce-a7f3-4bbe-93b9-e1abd2cfb964",
  "price": 100,
  "stock": 10,
  "productColors": ["ac161864-52f7-43d0-aca0-6a9282cd590e"],
  "productCategories": ["8a970a05-db91-47c7-9d84-4fc544aff01ess"],
  "productSizes": ["033ec480-a68b-44fb-8767-ccd7a7bcf3bd"],
  "productCategories": ["0d4c5955-6c3f-4817-9565-05df26c1d0fb"]
}

###
# @name get-all-products
GET {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###

# @name get-product-featured
GET {{BASE_URL}}/products/featured-products
Content-Type: application/json


###

# @name delete-product
DELETE {{BASE_URL}}/products/06e0dcdb-2843-4412-b1e9-950dc2a1b98f
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name get-product-by-id
GET {{BASE_URL}}/products/d624bc75-4f96-468d-a0c8-3c144e1ec65c


