@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name create-account
POST {{BASE_URL}}/accounts
Content-Type: application/json

{
  "name": "bruno",
  "email": "bru@bruno.com",
  "password":"123456"
}

###
# @name delete-account
DELETE {{BASE_URL}}/accounts/e5b4251e-ffdf-426b-9f81-f45d1645843d
Content-Type: application/json


###

# @name create-account-google
POST {{BASE_URL}}/accounts/google
Content-Type: application/json

{
  "name": "bruno",
  "email": "brunogmdaddifld@bruno.com",
  "googleUserId": "123456",
  "profileImageUrl": "https://www.google.com.br"
}


###

# @name check-if-email-exists
POST {{BASE_URL}}/accounts/check
Content-Type: application/json

{
  "email": "wbrunovieira17@gmail.com"
}


### 
# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "bru@bruno.com",
  "password": "123456"
}

###
# @name get-all-accounts
GET {{BASE_URL}}/accounts?page=1
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name create-products
POST {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "calcinha 8",
  "description": "calcinha 1 description",
  "color": "blue",
  "images": ["link1"],
  "size": "M",
  "material": "cotton",
  "brand": "brand 1",
  "price": 100.00,
  "stock": 10,
  "category": "lingerie",
  "discount": 15,
  "discountPrice": 85.00,
  "isNew": true,
  "isOnSale": true,
  "isFeatured": true
}


###
# @name get-all-products
GET {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}




