@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}



# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

###

# @name create-account
POST {{BASE_URL}}/accounts
Content-Type: application/json

{
  "name": "bruno",
  "email": "bru@bruno.com",
  "password":"123456aA@"
}

###



# @name update-account
PUT {{BASE_URL}}/accounts/27997069-e5ed-4af7-a428-e6f32c102c8e
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "email": "brunao@brunao.com"
 
}

###
# @name delete-account
DELETE {{BASE_URL}}/accounts/109eaa76-5b9b-4912-b2c9-e24d5c96eefa
Content-Type: application/json


###

# @name create-account-google
POST {{BASE_URL}}/accounts/google
Content-Type: application/json

{
  "name": "bruno",
  "email": "brunogmdaddifld@bruno.com",
  "googleUserId": "123456",
  "profileImageUrl": "https://www.google.com.br"
}


###

# @name check-if-email-exists
POST {{BASE_URL}}/accounts/check
Content-Type: application/json

{
  "email": "wbrunovieira17@gmail.com"
}


### 



# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

###
# @name get-all-accounts
GET {{BASE_URL}}/accounts?page=1
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

