@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

###

# @name create-color
POST {{BASE_URL}}/colors
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "blue"
}

###

# @name get-colors
GET  {{BASE_URL}}/colors
Content-Type: application/json

###

# @name delete-colors
Delete  {{BASE_URL}}/colors/5487c6ad-376b-4512-9461-f3814716f9ab
Content-Type: application/json

###

# @name find-color-by-id
GET  {{BASE_URL}}/colors/d1f4f8e2-d580-4f5c-ae75-e5df1648d409
Content-Type: application/json

###

# @name edit-color
PUT  {{BASE_URL}}/colors/b8ba2acd-10cf-4a87-83cd-4b9f9367199a
Content-Type: application/json

{
  "name": "rosinha"
  
}




