version: "3.9"  

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: stylos_app_prod
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      DB_HOST: stylos-db.czc0uc626uv5.us-east-1.rds.amazonaws.com
    ports:
      - "3333:3333"
    command: >
      sh -c "
      echo 'Aguardando conexão com o banco de dados no RDS...';
      while ! nc -z $DB_HOST 5432; do
        sleep 1;
      done;
      echo 'Conexão com o banco de dados estabelecida!';
      npx prisma generate;
      npx prisma migrate deploy;
      npm run start;
      "
