FROM node:20-buster

RUN apt-get update && apt-get install -y netcat postgresql-client

WORKDIR /app

RUN mkdir -p /app/data

COPY package*.json ./
COPY tsconfig.dev.json ./
COPY tsconfig.json ./
COPY nest-cli.json ./
COPY vitest.config*.ts ./
COPY .env.dev ./
COPY load_env.sh /app/load_env.sh
RUN chmod +x /app/load_env.sh

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3333

CMD ["sh", "/app/load_env.sh", "npx", "prisma", "migrate", "deploy", "--schema=/app/prisma/schema.prisma", "--dotenv", "/app/.env.dev"]

