version: "4.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: stylos_app_prod
    environment:
    - AWS_REGION=us-east-1
    - DATABASE_URL=ssm:///app/DATABASE_URL 
    ports:
      - "3333:3333"
