version: '3.8'
services:
  app:
    build: .
    container_name: stylos_backP
    volumes:
      - .:/app
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres

    container_name: stylos_db_prisma
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: stylos_db_prisma
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
