version: "4.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: stylos_app_prod
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    ports:
      - "3333:3333"
    command: >
        sh -c "
        chmod +x /app/start-prod.sh;
        ./start-prod.sh;
        "