@BASE_URL = http://localhost:3333

@AUTH_TOKEN = {{authenticate.response.body.access_token}}
# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Adminpassword@8"
}

###
# @name create-material
POST {{BASE_URL}}/materials
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "material 7"
  
}


###

# @name get-materials-by-name
GET  {{BASE_URL}}/materials/?name=material 5
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###

# @name get-all-materials
GET  {{BASE_URL}}/materials/all?page=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name delete-materials
Delete  {{BASE_URL}}/materials/3a53878a-9a6e-40cd-8234-3a0ceb54339c
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name find-material-by-id
GET  {{BASE_URL}}/materials/a6859f6b-bf57-48dd-a598-7d2b3a6f6b65
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name edit-material
PUT  {{BASE_URL}}/materials/e4685282-0b71-40d2-9665-e2bb3b6e8575
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "material 6"
  
}




