@BASE_URL = https://wbstylosbackend.sa.ngrok.io
@AUTH_TOKEN = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{BASE_URL}}/sessions/
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Adminpassword@8"
}

###

# @name get-orders-by-product
GET {{BASE_URL}}/orders/product/155d83d6-3ed1-479c-8c92-4fe26e3d566d
Content-Type: application/json


###
# @name get-orders-all
GET {{BASE_URL}}/orders/all?
Content-Type: application/json


###

# @name get-order-by-user
GET {{BASE_URL}}/orders/user/0e57489a-1f0a-422d-8549-59b40ca3ca8d
Content-Type: application/json

###

# @name get-orders-by-id
GET {{BASE_URL}}/orders/order/490c5f9a-4980-4ad3-98e7-83483017a3e4
Content-Type: application/json
