@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}



# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Adminpassword@8"
}


###

# @name create-products
POST {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "saia 12",
  "description": "calcinha description 1 mais texto, legal, muiito legal" ,
  "images": ["/images/foto1.jpg"],
  "materialId": "54ce261d-8f43-49e0-a610-658d75c9a211",
  "brandId": "bdc60ff1-29fb-460e-b9ba-e340c694c463",
  "sku":"12121212aa",
  "price": 100,
  "stock": 10,
  "height":11,
  "width":17,
  "length":11,
  "weight":0.3,
  
  "productColors": ["247b00b5-0b96-4713-a17c-8d05cf89fead"],
  "productCategories": ["b745e76b-4cbb-48ee-b3db-a6f1610dd572"],
  "productSizes": [ "f4051ddb-e807-4f8f-8f50-6f3f06d7795d"]
  
}

###

# @name get-all-products
GET {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###

# @name get-product-featured
GET {{BASE_URL}}/products/featured-products
Content-Type: application/json


###

# @name delete-product
DELETE {{BASE_URL}}/products/06e0dcdb-2843-4412-b1e9-950dc2a1b98f
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name get-product-by-id
GET {{BASE_URL}}/products/76fa1262-c5b2-4f81-9ed1-bf9708d22412


