@BASE_URL = http://localhost:3333
@AUTH_TOKEN = {{authenticate.response.body.access_token}}



# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Adminpassword@8"
}


###

# @name create-products
POST {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "saia 12",
  "description": "calcinha description 1 mais texto, legal, muiito legal" ,
  "images": ["/images/foto1.jpg"],
  "materialId": "fa4c1be1-e130-4d9b-afb1-29f9b7cfaed7",
  "brandId": "bac943e7-e787-4994-a329-2555c94d10eb",
  "sku":"12121212aa",
  "price": 100,
  "stock": 10,
  "height":11,
  "width":17,
  "length":11,
  "weight":0.3,
  
  "productColors": ["28c3ce8f-a6e3-4cd1-b78e-8cf9408d0636","ac8c7ffb-7ede-4891-86e7-149c2c04ab0f"],
  "productCategories": ["68b26463-67c1-4db2-a506-42e5262c2ba9"],
  "productSizes": ["3786cfb9-d200-4f37-9144-4b94d79d713c", "dec68532-0b4e-4395-ac7a-0163be08f796"]
  
}

###

# @name get-all-products
GET {{BASE_URL}}/products
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}


###

# @name get-product-featured
GET {{BASE_URL}}/products/featured-products
Content-Type: application/json


###

# @name delete-product
DELETE {{BASE_URL}}/products/06e0dcdb-2843-4412-b1e9-950dc2a1b98f
Authorization: Bearer {{AUTH_TOKEN}}

###

# @name get-product-by-id
GET {{BASE_URL}}/products/d624bc75-4f96-468d-a0c8-3c144e1ec65c


