@BASE_URL = http://localhost:3333

# @name create-size
POST {{BASE_URL}}/size
Content-Type: application/json

{
  "name": "g"
  
}

###

# @name get-size
GET  {{BASE_URL}}/size
Content-Type: application/json

###

# @name delete-size
Delete  {{BASE_URL}}/size/b0c8de50-35b9-4883-bb3b-e50942735736
Content-Type: application/json

###

# @name find-size-by-id
GET  {{BASE_URL}}/size/5a40ebc4-e091-4938-9213-a8bd602d7208
Content-Type: application/json

###

# @name edit-size
PUT  {{BASE_URL}}/size/5a40ebc4-e091-4938-9213-a8bd602d7208
Content-Type: application/json

{
  "name": "m"
  
}




