- name: Ensure Certbot is installed
  ansible.builtin.apt:
      name:
          - certbot
          - python3-certbot-nginx
      state: present

- name: Obtain SSL certificates for api.styloslingerie.com.br
  ansible.builtin.command:
      cmd: >
          certbot certonly --nginx
          -d api.styloslingerie.com.br
          --non-interactive
          --agree-tos
          -m your-email@example.com
      creates: /etc/letsencrypt/live/api.styloslingerie.com.br/fullchain.pem
  register: certbot_output
  changed_when: certbot_output.rc == 0

- name: Configure Nginx as a reverse proxy for the API
  ansible.builtin.copy:
      dest: /etc/nginx/sites-available/styloslingerie
      content: |
          # HTTP to HTTPS redirect for API
          server {
              listen 80;
              server_name api.styloslingerie.com.br;

              location / {
                  return 301 https://$host$request_uri;
              }

              location ~ /\. {
                  deny all;
              }
          }

          # HTTPS configuration for API
          server {
              listen 443 ssl;
              server_name api.styloslingerie.com.br;

              ssl_certificate /etc/letsencrypt/live/api.styloslingerie.com.br/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/api.styloslingerie.com.br/privkey.pem;

              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;

              location /api/ {
                  proxy_pass http://127.0.0.1:3333/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;

                  proxy_read_timeout 600;
                  proxy_connect_timeout 600;
                  proxy_send_timeout 600;
              }

              location / {
                  return 404;
              }

              location ~ /\. {
                  deny all;
              }
          }
      mode: "0644"
  notify:
      - Restart Nginx

- name: Remove default Nginx site if exists
  ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  notify: Restart Nginx

- name: Enable Nginx site configuration
  ansible.builtin.file:
      src: /etc/nginx/sites-available/styloslingerie
      dest: /etc/nginx/sites-enabled/styloslingerie
      state: link
      force: true

- name: Test Nginx configuration
  ansible.builtin.command:
      cmd: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: "'syntax is ok' not in nginx_test.stderr or 'test is successful' not in nginx_test.stderr"
  notify:
      - Restart Nginx

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
