- name: Configure Nginx as a reverse proxy
  ansible.builtin.copy:
      dest: /etc/nginx/sites-available/styloslingerie
      content: |
          # HTTP to HTTPS redirect
          server {
              listen 80;
              server_name styloslingerie.com.br www.styloslingerie.com.br;
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name styloslingerie.com.br www.styloslingerie.com.br;
              ssl_certificate /etc/letsencrypt/live/styloslingerie.com.br/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/styloslingerie.com.br/privkey.pem;

              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;
              ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
              ssl_ecdh_curve secp384r1;
              ssl_session_timeout  10m;
              ssl_session_cache shared:SSL:10m;
              ssl_session_tickets off;
              ssl_stapling on;
              ssl_stapling_verify on;

              proxy_read_timeout 600;
              proxy_connect_timeout 600;
              proxy_send_timeout 600;

              location / {
                  proxy_pass http://127.0.0.1:3000/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /api/ {
                  rewrite ^/api/(.*)$ /$1 break;
                  proxy_pass http://127.0.0.1:3333;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

          }

      mode: "0644"
  notify:
      - Restart Nginx

- name: Remove default Nginx site if exists
  ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  notify: Restart Nginx

- name: Enable Nginx site configuration
  ansible.builtin.file:
      src: /etc/nginx/sites-available/styloslingerie
      dest: /etc/nginx/sites-enabled/styloslingerie
      state: link
      force: true

- name: Test Nginx configuration
  ansible.builtin.command:
      cmd: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: "'syntax is ok' not in nginx_test.stderr or 'test is successful' not in nginx_test.stderr"

  notify:
      - Restart Nginx

- name: Ensure Nginx service is stopped
  ansible.builtin.service:
      name: nginx
      state: stopped

- name: Wait for Nginx to stop
  ansible.builtin.wait_for:
      port: 80
      state: stopped
      timeout: 30

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

- name: Wait for Nginx to start
  ansible.builtin.wait_for:
      port: 80
      timeout: 30

- name: Check Nginx status
  ansible.builtin.command:
      cmd: systemctl status nginx
  register: nginx_status
  changed_when: false
  ignore_errors: true

- name: Debug Nginx status
  ansible.builtin.debug:
      var: nginx_status.stdout_lines
