- name: Install Certbot
  ansible.builtin.apt:
      name:
          - certbot
          - python3-certbot-nginx
      state: present

- name: Obtain SSL certificates for domains
  ansible.builtin.command:
      cmd: >
          certbot --nginx
          {% for domain in common_certbot_domains -%}
          -d {{ domain }}
          {% endfor -%}
          --non-interactive
          --agree-tos
          -m "{{ common_certbot_email }}"
  args:
      creates: /etc/letsencrypt/live/{{ common_certbot_domains[0] }}/fullchain.pem
  register: certbot_output
  changed_when: >
      certbot_output.rc == 0 and
      ('Congratulations' in certbot_output.stdout or
      'Certificate not yet due for renewal' in certbot_output.stdout)

- name: Debug Certbot Output
  ansible.builtin.debug:
      msg: "{{ certbot_output.stdout_lines }}"

- name: Configure automatic certificate renewal
  ansible.builtin.cron:
      name: "Certbot automatic renewal"
      job: "certbot renew --quiet"
      minute: "0"
      hour: "1,13"
      user: root
