- name: Restart Nginx
  ansible.builtin.service:
      name: nginx
      state: restarted

- name: Restart sysstat
  ansible.builtin.systemd:
      name: sysstat
      state: restarted

- name: Restart Fail2Ban
  ansible.builtin.service:
      name: fail2ban
      state: restarted
