- name: Initial server setup
  hosts: all
  become: true
  gather_facts: true
  gather_subset:
      - min
      - network
  gather_timeout: 10
  vars_files:
      - secrets.yml
      - roles/frontend/vars/main.yml

  roles:
      - backend
      - common
      - frontend
