- name: Initial server setup
  hosts: all
  become: true
  tasks:
    - name: Ensure growpart is installed (for resizing partition)
      apt:
        name: cloud-guest-utils
        state: present

    - name: Check current disk and partition details
      command: lsblk -b --noheadings --raw -o NAME,SIZE,MOUNTPOINT
      register: disk_info
      changed_when: false

    - name: Debug disk info
      debug:
        var: disk_info.stdout_lines

    - name: Parse current root partition size
      set_fact:
        root_partition_size: >-
          {{ (disk_info.stdout_lines | select('search', '^nvme0n1p1 ') | map('split') | list | first)[1] | int(default=0) }}
        disk_size: >-
          {{ (disk_info.stdout_lines | select('search', '^nvme0n1 ') | map('split') | list | first)[1] | int(default=0) }}

    - name: Debug parsed sizes
      debug:
        msg:
          - "Root partition size: {{ root_partition_size }} bytes"
          - "Disk size: {{ disk_size }} bytes"

    - name: Resize the filesystem to match the new partition size
      command: resize2fs /dev/nvme0n1p1
      when: root_partition_size < disk_size
      register: resize2fs_result

    - name: Debug resize2fs output
      debug:
        var: resize2fs_result.stdout_lines

    - name: Ensure the filesystem is resized
      command: df -h /
      register: filesystem_info

    - name: Debug filesystem info
      debug:
        var: filesystem_info.stdout_lines
    
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install essential packages
      apt:
        name:
          - curl
          - wget
          - unzip
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker CLI plugins directory exists
      file:
        path: /usr/libexec/docker/cli-plugins
        state: directory
        mode: '0755'    

    - name: Verify Docker Compose Installation
      command: /usr/local/bin/docker-compose --version

    - name: Ensure /usr/local/bin is in PATH
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:/usr/local/bin'
        state: present

    - name: Ensure Docker Compose is available as a Docker subcommand
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        state: link  

    - name: Check if swap is already configured
      command: swapon --show
      register: swap_status
      changed_when: false

    - name: Create a 2GB swap file if not exists
      command: fallocate -l 2G /swapfile
      args:
        creates: /swapfile
      when: swap_status.stdout == ""

    - name: Secure the swap file
      file:
        path: /swapfile
        mode: '0600'
      when: swap_status.stdout == ""

    - name: Format the swap file
      command: mkswap /swapfile
      when: swap_status.stdout == ""

    - name: Activate the swap file
      command: swapon /swapfile
      when: swap_status.stdout == ""

    - name: Ensure the swap is enabled at boot
      lineinfile:
        path: /etc/fstab
        line: "/swapfile none swap sw 0 0"
        state: present

    - name: Clone or update the project from GitHub
      git:
        repo: "https://github.com/wbrunovieira/StylosEcommerceBackendPrismaNestJS.git"
        dest: /opt/StylosEcommerceBackendPrismaNestJS
        update: yes

    - name: Ensure target directory exists for .env.production
      file:
        path: /opt/StylosEcommerceBackendPrismaNestJS
        state: directory
        mode: '0755'

    - name: Copy .env.production to the server
      copy:
        src: /home/wbruno/projects/StylosEcommerceBackendPrismaNestJS/.env.production
        dest: /opt/StylosEcommerceBackendPrismaNestJS/.env.production
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Start the production Docker Compose services
      shell: |
        cd /opt/StylosEcommerceBackendPrismaNestJS
        docker compose -f docker-compose.prod.yml up -d
      args:
        executable: /bin/bash
