- name: Install sysstat package
  ansible.builtin.apt:
      name: sysstat
      state: present

- name: Enable and start sysstat service
  ansible.builtin.systemd:
      name: sysstat
      enabled: true
      state: started

- name: Set sysstat data retention to 7 days (Debian-based systems)
  ansible.builtin.replace:
      path: /etc/default/sysstat
      regexp: "^HISTORY=[0-9]+"
      replace: "HISTORY=7"
  when: ansible_facts.pkg_mgr == 'apt'
  notify: Restart sysstat

- name: Set sysstat collection interval to 1 minute
  ansible.builtin.lineinfile:
      path: /etc/cron.d/sysstat
      regexp: "^."
      line: "/1 * * * * root /usr/lib64/sa/sa1 1 1"
      state: present
  notify: Restart sysstat

- name: Install procps package for vmstat
  ansible.builtin.apt:
      name: procps
      state: present

- name: Create vmstat monitoring script
  ansible.builtin.copy:
      dest: /usr/local/bin/monitor_vmstat.sh
      content: |
          #!/bin/bash
          vmstat 1 10 >> /var/log/vmstat.log
      mode: "0755"

- name: Schedule vmstat monitoring script execution
  ansible.builtin.cron:
      name: "Vmstat monitoring"
      minute: "*/5"
      job: "/usr/local/bin/monitor_vmstat.sh"

- name: Ensure sysstat service is running
  ansible.builtin.service:
      name: sysstat
      state: started
      enabled: true
